import { useEffect, useState } from 'react'
import { Link, Route, Routes, useLocation } from 'react-router-dom'
import { ArrowRight, CalendarDays, CheckCircle2, ChevronDown, Clock3, ExternalLink, MapPin, Menu, Phone, ShieldCheck, Stethoscope, X } from 'lucide-react'
import { chamber as defaultChamber, contacts as defaultContacts, doctor as defaultDoctor, services as defaultServices } from './data'
import { getPublicContent, submitAppointment } from './services/api'

function NavBar() {
  const [open, setOpen] = useState(false)
  const location = useLocation()
  const links = [['home', 'হোম'], ['about', 'ডাক্তার সম্পর্কে'], ['services', 'সার্জিক্যাল সেবা'], ['chamber', 'চেম্বার'], ['appointment', 'অ্যাপয়েন্টমেন্ট'], ['gallery', 'গ্যালারি'], ['contact', 'যোগাযোগ']]
  const go = (id) => { setOpen(false); if (location.pathname !== '/') window.location.href = `/#${id}` }
  return <header className="site-header"><div className="container nav-wrap"><Link to="/#home" className="brand" onClick={() => setOpen(false)}><span className="brand-mark"><Stethoscope size={21} /></span><span><strong>ডাঃ আলমগীর জলিল</strong><small>ল্যাপারোস্কোপিক সার্জারি</small></span></Link><button className="menu-toggle" aria-label="মেনু" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><nav className={open ? 'nav-links is-open' : 'nav-links'}>{links.map(([id, label]) => <a href={`#${id}`} key={id} onClick={() => go(id)}>{label}</a>)}<a className="nav-call" href={`tel:${defaultContacts.serial}`}><Phone size={16} /> কল করুন</a></nav></div></header>
}

function SectionHeading({ eyebrow, title, copy, light = false }) { return <div className={light ? 'section-heading light' : 'section-heading'}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div> }

function Hero({ doctor, contacts }) { return <section id="home" className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="availability"><span className="pulse-dot" /> রোগী দেখার জন্য যোগাযোগ করুন</div><p className="kicker">ল্যাপারোস্কোপিক সার্জারি বিশেষজ্ঞ</p><h1>{doctor.name}</h1><div className="doctor-role"><span>{doctor.designation}</span><span>{doctor.institution}</span></div><p className="hero-intro">{doctor.introduction}</p><div className="hero-actions"><a href="#appointment" className="button button-primary">অ্যাপয়েন্টমেন্ট নিন <ArrowRight size={18} /></a><a href={`tel:${contacts.serial}`} className="button button-outline"><Phone size={17} /> {contacts.serial}</a></div><div className="hero-note"><ShieldCheck size={19} /><span>রোগীর প্রয়োজন অনুযায়ী যত্নশীল পরামর্শ ও চিকিৎসা পরিকল্পনা</span></div></div><div className="hero-visual"><div className="image-frame"><img src={doctor.image} alt={doctor.name} /><div className="image-caption"><span className="caption-icon"><Stethoscope size={20} /></span><div><strong>সার্জারি বিভাগ</strong><small>রংপুর মেডিকেল কলেজ হাসপাতাল</small></div></div></div><div className="hero-accent accent-one" /><div className="hero-accent accent-two" /></div></div></section> }

function About({ doctor }) { return <section id="about" className="section about-section"><div className="container"><SectionHeading eyebrow="ডাক্তার সম্পর্কে" title="অভিজ্ঞতার চেয়ে গুরুত্বপূর্ণ হলো সঠিক মনোযোগ" copy="প্রতিটি রোগীর জন্য প্রয়োজনীয় তথ্য, পরামর্শ এবং চিকিৎসা পরিকল্পনা বুঝে নেওয়াই আমাদের অগ্রাধিকার।" /><div className="about-grid"><div className="about-quote"><span className="quote-mark">“</span><p>{doctor.introduction}</p><div className="signature-line"><span />{doctor.name}</div></div><div className="info-list"><div className="info-row"><span className="info-icon"><Clock3 /></span><div><b>অভিজ্ঞতা</b><p>তথ্য শীঘ্রই আপডেট করা হবে</p></div></div><div className="info-row"><span className="info-icon"><ShieldCheck /></span><div><b>শিক্ষাগত যোগ্যতা</b><p>তথ্য শীঘ্রই আপডেট করা হবে</p></div></div></div></div></div></section> }

function Services({ services }) { return <section id="services" className="section services-section"><div className="container"><SectionHeading eyebrow="সার্জিক্যাল সেবা" title="প্রয়োজনীয় যত্ন, পরিষ্কার ব্যাখ্যা" copy="আপনার সমস্যার ধরন বুঝে উপযুক্ত সার্জিক্যাল পরামর্শের জন্য যোগাযোগ করুন।" /><div className="service-grid">{services.map((service, index) => <article className="service-card" key={service.title}><div className="service-number">0{index + 1}</div><div className="service-icon">{service.icon}</div><h3>{service.title}</h3><p>{service.description}</p><a href="#appointment">আলোচনা করুন <ArrowRight size={16} /></a></article>)}</div></div></section> }

function Chamber({ chamber, contacts }) { return <section id="chamber" className="section chamber-section"><div className="container chamber-grid"><div><SectionHeading eyebrow="চেম্বার তথ্য" title="আপনার সুবিধার জন্য নির্দিষ্ট সময়" copy="চেম্বারে আসার আগে সিরিয়ালের জন্য যোগাযোগ করে সময় নিশ্চিত করে নিন।" /><div className="chamber-details"><div className="detail-item"><MapPin /><div><small>চেম্বার</small><strong>{chamber.name}</strong><span>{chamber.address}</span></div></div><div className="detail-item"><Clock3 /><div><small>ভিজিটিং আওয়ার</small><strong>{chamber.visitingHours}</strong><span>{chamber.visitingDays}</span></div></div><div className="detail-item"><Phone /><div><small>সিরিয়ালের জন্য</small><a href={`tel:${contacts.serial}`}>{contacts.serial}</a><span>ফোনে যোগাযোগ করুন</span></div></div></div><a href={chamber.mapUrl} target="_blank" rel="noreferrer" className="text-link">Google Maps এ লোকেশন দেখুন <ExternalLink size={16} /></a></div><div className="map-card"><div className="map-content"><MapPin size={34} /><strong>{chamber.name}</strong><span>{chamber.address}</span><a href={chamber.mapUrl} target="_blank" rel="noreferrer" className="button button-light">দিকনির্দেশনা নিন <ArrowRight size={17} /></a></div></div></div></section> }

function Appointment() { const [form, setForm] = useState({ patientName: '', phone: '', preferredDate: '', preferredTime: '', message: '', email: '' }); const [state, setState] = useState({ loading: false, success: '', error: '' }); const update = (e) => setForm({ ...form, [e.target.name]: e.target.value }); const submit = async (e) => { e.preventDefault(); setState({ loading: true, success: '', error: '' }); try { await submitAppointment(form); setState({ loading: false, success: 'আপনার সিরিয়াল অনুরোধ সফলভাবে পাঠানো হয়েছে। প্রয়োজন অনুযায়ী কর্তৃপক্ষ আপনার সাথে যোগাযোগ করবে।', error: '' }); setForm({ patientName: '', phone: '', preferredDate: '', preferredTime: '', message: '', email: '' }) } catch { setState({ loading: false, success: '', error: 'অনুরোধ পাঠানো যায়নি। অনুগ্রহ করে ফোনে যোগাযোগ করুন।' }) } }; return <section id="appointment" className="section appointment-section"><div className="container appointment-grid"><div className="appointment-copy"><SectionHeading eyebrow="অ্যাপয়েন্টমেন্ট" title="আপনার সুবিধামতো সিরিয়াল অনুরোধ করুন" copy="ফর্মটি পূরণ করুন। এটি একটি অনুরোধ, অ্যাপয়েন্টমেন্ট নিশ্চিত হওয়ার জন্য কর্তৃপক্ষের যোগাযোগের অপেক্ষা করুন।" /><div className="appointment-points"><span><CheckCircle2 /> প্রয়োজনীয় তথ্য দিন</span><span><CheckCircle2 /> ফোনে সময় নিশ্চিত করুন</span></div></div><form className="appointment-form" onSubmit={submit}><div className="form-row"><label>রোগীর নাম<input name="patientName" value={form.patientName} onChange={update} required placeholder="আপনার নাম" /></label><label>মোবাইল নম্বর<input name="phone" type="tel" value={form.phone} onChange={update} required placeholder="০১৭৮৮-০৪৪২৭৯" /></label></div><div className="form-row"><label>পছন্দের তারিখ<input name="preferredDate" type="date" value={form.preferredDate} onChange={update} required /></label><label>পছন্দের সময়<input name="preferredTime" type="time" value={form.preferredTime} onChange={update} required /></label></div><label>ইমেইল <span className="optional">(ঐচ্ছিক)</span><input name="email" type="email" value={form.email} onChange={update} placeholder="you@example.com" /></label><label>সমস্যা / বার্তা<textarea name="message" value={form.message} onChange={update} rows="3" placeholder="আপনার সমস্যাটি সংক্ষেপে লিখুন" /></label>{state.success && <div className="form-message success">{state.success}</div>}{state.error && <div className="form-message error">{state.error}</div>}<button className="button button-primary submit-button" disabled={state.loading}>{state.loading ? 'পাঠানো হচ্ছে...' : 'সিরিয়াল অনুরোধ পাঠান'} <ArrowRight size={18} /></button></form></div></section> }

function Gallery() { return <section id="gallery" className="section gallery-section"><div className="container"><div className="gallery-heading"><SectionHeading eyebrow="গ্যালারি" title="চিকিৎসা সেবার একটি পরিচিত পরিবেশ" copy="প্রফেশনাল পরিবেশ ও চেম্বার সম্পর্কে ধারণা পেতে আমাদের গ্যালারি দেখুন।" /><span className="gallery-count">০৩<br /><small>ছবি</small></span></div><div className="gallery-grid"><img className="gallery-wide" src="/assets/gallery.jpg" alt="ল্যাপারোস্কোপিক সার্জারি সেবা" loading="lazy" /><img src="/assets/services.jpg" alt="সার্জিক্যাল সেবার তথ্য" loading="lazy" /><img src="/assets/doctor.jpg" alt="ডাঃ মোঃ আলমগীর জলিল প্রামাণিক" loading="lazy" /></div></div></section> }

function Emergency({ contacts }) { return <section id="contact" className="emergency-section"><div className="container emergency-inner"><div><span className="eyebrow">জরুরি যোগাযোগ</span><h2>প্রয়োজনে সরাসরি যোগাযোগ করুন</h2><p>জরুরি প্রয়োজনে নিচের নম্বরে কল করুন।</p></div><a href={`tel:${contacts.emergency}`} className="emergency-number"><span><Phone size={20} /></span><div><small>জরুরি নম্বর</small><strong>{contacts.emergency}</strong></div></a></div></section> }

function Footer({ doctor, contacts, chamber }) { return <footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><Link to="/#home" className="brand"><span className="brand-mark"><Stethoscope size={21} /></span><span><strong>{doctor.name}</strong><small>{doctor.specialization}</small></span></Link><p>সঠিক পরামর্শ ও প্রয়োজনীয় সার্জিক্যাল সেবার জন্য যোগাযোগ করুন।</p></div><div><h4>দ্রুত লিংক</h4><a href="#about">ডাক্তার সম্পর্কে</a><a href="#services">সার্জিক্যাল সেবা</a><a href="#chamber">চেম্বার তথ্য</a><a href="#appointment">অ্যাপয়েন্টমেন্ট</a></div><div><h4>যোগাযোগ</h4><a href={`tel:${contacts.serial}`}><Phone size={15} /> {contacts.serial}</a><a href={`tel:${contacts.emergency}`}><Phone size={15} /> {contacts.emergency}</a><span><MapPin size={15} /> {chamber.name}, {chamber.address}</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} {doctor.name}</span><span>সর্বস্বত্ব সংরক্ষিত</span></div></footer> }

function FloatingActions({ contacts }) { return <div className="floating-actions"><a href={`https://wa.me/${contacts.whatsapp}?text=${encodeURIComponent('আসসালামু আলাইকুম, অ্যাপয়েন্টমেন্টের জন্য যোগাযোগ করছি।')}`} target="_blank" rel="noreferrer" className="float-whatsapp" aria-label="WhatsApp">WA</a><a href={`tel:${contacts.serial}`} className="float-call" aria-label="কল করুন"><Phone size={20} /></a></div> }

function Home() { const [content, setContent] = useState({ doctor: defaultDoctor, contacts: defaultContacts, services: defaultServices, chamber: defaultChamber }); useEffect(() => { getPublicContent().then(data => setContent(prev => ({ ...prev, ...data }))).catch(() => {}) }, []); return <><NavBar /><main><Hero doctor={content.doctor} contacts={content.contacts} /><About doctor={content.doctor} /><Services services={content.services} /><Chamber chamber={content.chamber} contacts={content.contacts} /><Appointment /><Emergency contacts={content.contacts} /><Gallery /></main><Footer doctor={content.doctor} contacts={content.contacts} chamber={content.chamber} /><FloatingActions contacts={content.contacts} /></> }

function AdminLogin() { return <main className="admin-page"><div className="admin-box"><span className="brand-mark"><Stethoscope size={22} /></span><h1>অ্যাডমিন লগইন</h1><p>ওয়েবসাইট কনটেন্ট পরিচালনার জন্য প্রবেশ করুন।</p><form><label>ইমেইল<input type="email" placeholder="admin@example.com" /></label><label>পাসওয়ার্ড<input type="password" placeholder="••••••••" /></label><button className="button button-primary">প্রবেশ করুন <ArrowRight size={17} /></button></form><Link to="/" className="text-link">মূল ওয়েবসাইটে ফিরুন</Link></div></main> }

function AdminDashboard() { return <main className="admin-page"><div className="admin-dashboard"><div className="admin-dashboard-head"><div><span className="eyebrow">কনটেন্ট ম্যানেজমেন্ট</span><h1>ড্যাশবোর্ড</h1><p>ওয়েবসাইটের গুরুত্বপূর্ণ বিষয়গুলো এক জায়গা থেকে পরিচালনা করুন।</p></div><Link to="/" className="button button-outline">সাইট দেখুন <ExternalLink size={16} /></Link></div><div className="admin-stats"><div><span>সার্জিক্যাল সেবা</span><strong>০৫</strong></div><div><span>চেম্বার</span><strong>০১</strong></div><div><span>অ্যাপয়েন্টমেন্ট</span><strong>--</strong></div><div><span>গ্যালারি ছবি</span><strong>০৩</strong></div></div><div className="admin-panels"><section><h2>দ্রুত ব্যবস্থাপনা</h2><button>ডাক্তার প্রোফাইল <ChevronDown size={16} /></button><button>সার্জিক্যাল সেবা <ChevronDown size={16} /></button><button>চেম্বার তথ্য <ChevronDown size={16} /></button><button>যোগাযোগের তথ্য <ChevronDown size={16} /></button></section><section><h2>সাম্প্রতিক অ্যাপয়েন্টমেন্ট</h2><div className="admin-empty"><CalendarDays size={25} /><p>নতুন সিরিয়াল অনুরোধ এখানে দেখা যাবে।</p><small>MongoDB সংযোগ ও অথেনটিকেশন কনফিগার করুন</small></div></section></div></div></main> }

function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/admin/login" element={<AdminLogin />} /><Route path="/admin/dashboard" element={<AdminDashboard />} /></Routes> }

export default App
