export const content = {
  bn: {
    brand: 'ডাঃ আলমগীর জলিল', specialty: 'ল্যাপারোস্কোপিক সার্জারি',
    nav: { home: 'হোম', about: 'ডাক্তারের সম্পর্কে', services: 'সার্জিক্যাল সেবা', chamber: 'চেম্বার', appointment: 'অ্যাপয়েন্টমেন্ট', gallery: 'গ্যালারি', contact: 'যোগাযোগ', call: 'কল করুন' },
    doctor: { name: 'ডাঃ মোঃ আলমগীর জলিল প্রামাণিক', designation: 'সহকারী অধ্যাপক, সার্জারি বিভাগ', institution: 'রংপুর মেডিকেল কলেজ হাসপাতাল, রংপুর', specialization: 'ল্যাপারোস্কোপিক সার্জন / ল্যাপারোস্কোপিক সার্জারি বিশেষজ্ঞ', introduction: 'ডাঃ মোঃ আলমগীর জলিল প্রামাণিক একজন ল্যাপারোস্কোপিক সার্জন এবং সার্জারি বিভাগের সহকারী অধ্যাপক। তিনি আধুনিক ল্যাপারোস্কোপিক পদ্ধতিতে বিভিন্ন ধরনের সার্জিক্যাল রোগের চিকিৎসা ও অপারেশন সেবা প্রদান করেন।', image: '/assets/doctor.jpg' },
    contacts: { serial: '01788-044279', emergency: '0155-9617223', whatsapp: '8801788044279' },
    chamber: { name: 'মাউন্ট প্যাসিফিক হাসপাতাল', address: 'রংপুর, বাংলাদেশ', visitingDays: 'শীঘ্রই আপডেট করা হবে', visitingHours: 'বিকাল ৩টা থেকে রাত ৮টা পর্যন্ত', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mount+Pacific+Hospital+Rangpur+Bangladesh' },
    services: [
      ['ল্যাপারোস্কোপিক গলব্লাডার (পিত্তথলি) অপারেশন', 'পিত্তথলি সংক্রান্ত সমস্যার জন্য আধুনিক ল্যাপারোস্কোপিক সার্জারি সেবা।'],
      ['ল্যাপারোস্কোপিক অ্যাপেন্ডিসাইটিস অপারেশন', 'অ্যাপেন্ডিসাইটিসের প্রয়োজনীয় সার্জিক্যাল মূল্যায়ন ও অপারেশন সেবা।'],
      ['ল্যাপারোস্কোপিক হার্নিয়া অপারেশন', 'হার্নিয়া সমস্যার জন্য রোগীর প্রয়োজন অনুযায়ী সার্জিক্যাল পরামর্শ।'],
      ['ল্যাপারোস্কোপিক কোলন ও রেক্টাল সার্জারি', 'কোলন ও রেক্টাল সমস্যায় প্রাসঙ্গিক সার্জিক্যাল চিকিৎসা সেবা।'],
      ['অ্যাসিডিটি / আলসার / গ্যাস্ট্রিক সমস্যার সার্জারি', 'প্রয়োজন হলে সার্জিক্যাল পরামর্শ ও চিকিৎসা পরিকল্পনা।']
    ],
    ui: { availability:'রোগী দেখার জন্য যোগাযোগ করুন', appointment:'অ্যাপয়েন্টমেন্ট নিন', care:'রোগীর প্রয়োজন অনুযায়ী যত্নশীল পরামর্শ ও চিকিৎসা পরিকল্পনা', about:'ডাক্তারের সম্পর্কে', aboutTitle:'সঠিক মনোযোগই সবচেয়ে গুরুত্বপূর্ণ', aboutCopy:'প্রতিটি রোগীর প্রয়োজনীয় তথ্য, পরামর্শ এবং চিকিৎসা পরিকল্পনা বুঝে নেওয়াই আমাদের অগ্রাধিকার।', experience:'অভিজ্ঞতা', education:'শিক্ষাগত যোগ্যতা', pending:'তথ্য শীঘ্রই আপডেট করা হবে', services:'সার্জিক্যাল সেবা', servicesTitle:'প্রয়োজনীয় যত্ন, পরিষ্কার ব্যাখ্যা', servicesCopy:'আপনার সমস্যার ধরন বুঝে উপযুক্ত সার্জিক্যাল পরামর্শের জন্য যোগাযোগ করুন।', discuss:'আলোচনা করুন', chamber:'চেম্বার তথ্য', chamberTitle:'আপনার সুবিধার জন্য নির্দিষ্ট সময়', chamberCopy:'চেম্বারে আসার আগে সিরিয়ালের জন্য যোগাযোগ করে সময় নিশ্চিত করুন।', hours:'ভিজিটিং আওয়ার', serial:'সিরিয়ালের জন্য', phoneHelp:'ফোনে যোগাযোগ করুন', map:'Google Maps এ লোকেশন দেখুন', directions:'দিকনির্দেশনা নিন', formTitle:'আপনার সুবিধামতো সিরিয়াল অনুরোধ করুন', formCopy:'ফর্মটি পূরণ করুন। এটি একটি অনুরোধ; অ্যাপয়েন্টমেন্ট নিশ্চিত করার জন্য কর্তৃপক্ষের যোগাযোগের অপেক্ষা করুন।', patient:'রোগীর নাম', phone:'মোবাইল নম্বর', date:'পছন্দের তারিখ', time:'পছন্দের সময়', email:'ইমেইল', optional:'(ঐচ্ছিক)', message:'সমস্যা / বার্তা', namePlaceholder:'আপনার নাম', messagePlaceholder:'আপনার সমস্যাটি সংক্ষেপে লিখুন', send:'সিরিয়াল অনুরোধ পাঠান', sending:'পাঠানো হচ্ছে...', success:'আপনার সিরিয়াল অনুরোধ সফলভাবে পাঠানো হয়েছে।', error:'অনুরোধ পাঠানো যায়নি। অনুগ্রহ করে ফোনে যোগাযোগ করুন।', gallery:'গ্যালারি', galleryTitle:'চিকিৎসা সেবার একটি পরিচ্ছন্ন পরিবেশ', galleryCopy:'প্রফেশনাল পরিবেশ ও চেম্বার সম্পর্কে ধারণা পেতে আমাদের গ্যালারি দেখুন।', photos:'ছবি', emergency:'জরুরি যোগাযোগ', emergencyTitle:'প্রয়োজনে সরাসরি যোগাযোগ করুন', emergencyCopy:'জরুরি প্রয়োজনে নিচের নম্বরে কল করুন।', emergencyNumber:'জরুরি নম্বর', quick:'দ্রুত লিংক', rights:'সর্বস্বত্ব সংরক্ষিত', language:'ভাষা পরিবর্তন করুন', theme:'ডার্ক মোড চালু বা বন্ধ করুন', admin:'অ্যাডমিন লগইন', adminCopy:'ওয়েবসাইট কনটেন্ট পরিচালনার জন্য প্রবেশ করুন।', login:'প্রবেশ করুন', back:'মূল ওয়েবসাইটে ফিরুন' }
  },
  en: {
    brand: 'Dr. Alamgir Jalil', specialty: 'Laparoscopic Surgery',
    nav: { home: 'Home', about: 'About Doctor', services: 'Surgical Services', chamber: 'Chamber', appointment: 'Appointment', gallery: 'Gallery', contact: 'Contact', call: 'Call' },
    doctor: { name: 'Dr. Md. Alamgir Jalil Pramanik', designation: 'Assistant Professor, Department of Surgery', institution: 'Rangpur Medical College Hospital, Rangpur', specialization: 'Laparoscopic Surgeon / Laparoscopic Surgery Specialist', introduction: 'Dr. Md. Alamgir Jalil Pramanik is a laparoscopic surgeon and Assistant Professor in the Department of Surgery. He provides surgical care and operative services for a range of conditions using modern laparoscopic techniques.', image: '/assets/doctor.jpg' },
    contacts: { serial: '01788-044279', emergency: '0155-9617223', whatsapp: '8801788044279' },
    chamber: { name: 'Mount Pacific Hospital', address: 'Rangpur, Bangladesh', visitingDays: 'Not available yet', visitingHours: '3:00 PM – 8:00 PM', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mount+Pacific+Hospital+Rangpur+Bangladesh' },
    services: [
      ['Laparoscopic Gallbladder Surgery', 'Modern laparoscopic surgical care for gallbladder conditions.'], ['Laparoscopic Appendicitis Surgery', 'Surgical assessment and operative care for appendicitis.'], ['Laparoscopic Hernia Surgery', 'Surgical consultation tailored to the patient’s needs for hernia conditions.'], ['Laparoscopic Colon & Rectal Surgery', 'Relevant surgical care for colon and rectal conditions.'], ['Surgery for Acidity, Ulcer and Other Gastric Conditions', 'Surgical consultation and treatment planning when required.']
    ],
    ui: { availability:'Contact for appointments', appointment:'Book an appointment', care:'Thoughtful consultation and treatment planning based on each patient’s needs', about:'About Doctor', aboutTitle:'Care begins with careful attention', aboutCopy:'Understanding each patient’s information, concerns and care plan is our priority.', experience:'Experience', education:'Education & qualifications', pending:'Information will be updated soon', services:'Surgical Services', servicesTitle:'Thoughtful care, clear guidance', servicesCopy:'Contact us for appropriate surgical advice based on your condition.', discuss:'Discuss your care', chamber:'Chamber Information', chamberTitle:'Set hours for your convenience', chamberCopy:'Please contact us to confirm your appointment time before visiting the chamber.', hours:'Visiting hours', serial:'For serial', phoneHelp:'Contact by phone', map:'View location on Google Maps', directions:'Get directions', formTitle:'Request an appointment at your convenience', formCopy:'Complete the form. This is a request; please wait for the office to contact you to confirm an appointment.', patient:'Patient name', phone:'Mobile number', date:'Preferred date', time:'Preferred time', email:'Email', optional:'(optional)', message:'Concern / message', namePlaceholder:'Your name', messagePlaceholder:'Briefly describe your concern', send:'Send appointment request', sending:'Sending...', success:'Your appointment request was sent successfully.', error:'Your request could not be sent. Please contact us by phone.', gallery:'Gallery', galleryTitle:'A welcoming care environment', galleryCopy:'Explore our gallery for a glimpse of the professional setting and chamber.', photos:'Photos', emergency:'Emergency contact', emergencyTitle:'Contact us directly when needed', emergencyCopy:'For urgent needs, call the number below.', emergencyNumber:'Emergency number', quick:'Quick links', rights:'All rights reserved', language:'Change language', theme:'Toggle dark mode', admin:'Admin login', adminCopy:'Sign in to manage website content.', login:'Sign in', back:'Return to website' }
  }
}
